// High-level constructs for AWS CDK
package cloudstructs


// Properties for a SamlProvider.
// Deprecated: use `SamlProviderProps` from `aws-cdk-lib/aws-iam`.
type SamlIdentityProviderProps struct {
	// An XML document generated by an identity provider (IdP) that supports SAML 2.0.
	//
	// The document includes the issuer's name, expiration information, and keys that
	// can be used to validate the SAML authentication response (assertions) that are
	// received from the IdP. You must generate the metadata document using the identity
	// management software that is used as your organization's IdP.
	// Deprecated: use `SamlProviderProps` from `aws-cdk-lib/aws-iam`.
	MetadataDocument *string `field:"required" json:"metadataDocument" yaml:"metadataDocument"`
	// A name for the SAML identity provider.
	// Deprecated: use `SamlProviderProps` from `aws-cdk-lib/aws-iam`.
	Name *string `field:"optional" json:"name" yaml:"name"`
}

